const ACTION = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  CALL_LOGIN_SUCCESS: "CALL_LOGIN_SUCCESS",
  CALL_LOGIN_ERROR: "CALL_LOGIN_ERROR",
  CALL_SIGNUP_SUCCESS: "CALL_SIGNUP_SUCCESS",
  CALL_SIGNUP_ERROR: "CALL_SIGNUP_ERROR"
};

export default ACTION;
